%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 720
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 240.0
   fy: 240.0
   cx: 360.0
   cy: 240.0